services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  bresil-api:
    build: .
    ports:
      - "8001:3000"
    environment:
      PORT: 3000
      DB_PATH: /data/futurekawa.db
      PAYS: Bresil
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: futurekawa/bresil/#
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      RESPONSABLE_EMAIL: responsable-bresil@futurekawa.com
    volumes:
      - ../db:/data
    depends_on:
      mosquitto:
        condition: service_started
      mailhog:
        condition: service_started
    networks:
      - futurekawa_net

  equateur-api:
    build: .
    ports:
      - "8002:3000"
    environment:
      PORT: 3000
      DB_PATH: /data/futurekawa.db
      PAYS: Equateur
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: futurekawa/equateur/#
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      RESPONSABLE_EMAIL: responsable-equateur@futurekawa.com
    volumes:
      - ../db:/data
    depends_on:
      mosquitto:
        condition: service_started
      mailhog:
        condition: service_started
    networks:
      - futurekawa_net

  colombie-api:
    build: .
    ports:
      - "8003:3000"
    environment:
      PORT: 3000
      DB_PATH: /data/futurekawa.db
      PAYS: Colombie
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC: futurekawa/colombie/#
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      RESPONSABLE_EMAIL: responsable-colombie@futurekawa.com
    volumes:
      - ../db:/data
    depends_on:
      mosquitto:
        condition: service_started
      mailhog:
        condition: service_started
    networks:
      - futurekawa_net

networks:
  futurekawa_net:
    driver: bridge
